# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
    name='image_msg.proto',
    package='',
    serialized_pb='\n\x0fimage_msg.proto\".\n\nRequestMsg\x12\x0f\n\x07\x63ommand\x18\x01 \x02(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"@\n\x0bResponseMsg\x12\x0f\n\x07success\x18\x01 \x02(\x08\x12\x0f\n\x07\x63omment\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t')

_REQUESTMSG = descriptor.Descriptor(
    name='RequestMsg',
    full_name='RequestMsg',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        descriptor.FieldDescriptor(
            name='command', full_name='RequestMsg.command', index=0,
            number=1, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=unicode("", "utf-8"),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        descriptor.FieldDescriptor(
            name='content', full_name='RequestMsg.content', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=unicode("", "utf-8"),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    serialized_start=19,
    serialized_end=65,
)

_RESPONSEMSG = descriptor.Descriptor(
    name='ResponseMsg',
    full_name='ResponseMsg',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        descriptor.FieldDescriptor(
            name='success', full_name='ResponseMsg.success', index=0,
            number=1, type=8, cpp_type=7, label=2,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        descriptor.FieldDescriptor(
            name='comment', full_name='ResponseMsg.comment', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=unicode("", "utf-8"),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        descriptor.FieldDescriptor(
            name='content', full_name='ResponseMsg.content', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=unicode("", "utf-8"),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    serialized_start=67,
    serialized_end=131,
)

DESCRIPTOR.message_types_by_name['RequestMsg'] = _REQUESTMSG
DESCRIPTOR.message_types_by_name['ResponseMsg'] = _RESPONSEMSG


class RequestMsg(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _REQUESTMSG

    # @@protoc_insertion_point(class_scope:RequestMsg)


class ResponseMsg(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _RESPONSEMSG

    # @@protoc_insertion_point(class_scope:ResponseMsg)

# @@protoc_insertion_point(module_scope)
