# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-29 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlgCsv',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=64, unique=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.IntegerField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('depth', models.IntegerField()),
                ('probability', models.IntegerField()),
                ('classname', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'alg_csv',
                'managed': False,
            },
        ),
    ]
