class RefreshType(object):
    Image = 'image'
    Graphic = 'graphic'
    Crosshair = 'crosshair'
    Text = 'text'
    Mask = 'mask'
    WWWL = 'wwwl'
    SliceIndex = 'slice_index'
    BoundaryPts = 'boundary_pts'
    All = 'all'
